import MainHeader from '@/components/layout/MainHeader';
import './globals.css';

export const metadata = {
  title: 'NextEvent',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
